### ISSUE TITLE
Platform team outline #hex colour

### ISSUE THREAD

**Issue by browneyezz** [TeamTopologies/Team-Shape-Templates#16]
Just a minor thing, on the team shapes template page, the platform team outline HEX value (btw it says RGB, but it's HEX) is the same as the fill value.

![Screenshot 2021-07-01 at 12 49 19](https://user-images.githubusercontent.com/86778365/124112768-ed721f80-da6a-11eb-99b7-9889c45803cf.png)

**Comment by matthewskelton** [comment]
Fixed in #17 -thanks for raising this, @browneyezz 👍
