### ISSUE TITLE
Proposal for Lucid Chart template

### ISSUE THREAD

**Issue by mattkoch614** [TeamTopologies/Team-Shape-Templates#21]
Hi @matthewskelton  and @manupaisable ! Thank you for this superbly valuable resource. I am proposing adding support for Lucid Chart, and I went ahead and created the following template:

https://lucid.app/lucidchart/ee8afe63-92f7-4e56-8e05-f3d57846caae/edit?invitationId=inv_c87d42eb-17e4-4e8c-94a7-849d9c2c919a 

I've used Lucid Chart before at several organizations and figured it might be helpful to others using this tool.

**Comment by conjurer-rich** [comment]
Hi @mattkoch614,

Many thanks for this, it looks good. As it stands we could add a link to this under the [Community Supported Team Interaction Modelling Tools](https://github.com/TeamTopologies/Team-Shape-Templates#community-supported-team-interaction-modelling-tools) - for now please feel free to create a pull request following the same pattern as the Figma example.

Do you think it would also be possible to store the shape SVGs or stencils in this repository as per the Miro shapes so users could add them to a shape library and we can keep them version controlled? 

Many thanks

Rich

**Comment by mattkoch614** [comment]
Will do.
