### ISSUE TITLE
Figma template requires updating to include the Undefined Team Type shape

### ISSUE THREAD

**Issue by conjurer-rich** [TeamTopologies/Team-Shape-Templates#23]
A new Undefined Team Type shape has recently been introduced to enable a consistent representation of teams that have yet to be classified as one of the fundamental team types. 

The Figma template will need to be updated to include this.

**Comment by conjurer-rich** [comment]
@danmizziharris is this something you could do?

**Comment by danmizziharris** [comment]
@conjurer-rich I am no longer at Box UK.

Perhaps @houdmont can help with access or transferring ownership of the file?

**Comment by conjurer-rich** [comment]
It would be very handy if @houdmont would be able to help

**Comment by danmizziharris** [comment]
I have created a [draft](https://www.figma.com/file/ibYD7Nwqwnl559N7CFPK4L/Team-Topologies---Team-shapes-template-(Community)?node-id=3%3A41) of this.

+ Add `Undefined Team Type` symbol
+ Add `Supplementary Team types` section to the template
+ Increase length of the dashes to increase the contrast with the new dotted line style.

I have emailed Tom to see if we can sort it out together soon :)

**Comment by houdmont** [comment]
Thanks @danmizziharris, the team have updated the template and published the changes now so it should all be up to date.

Thanks for letting us know! 

@conjurer-rich let us know if there's anything we missed that you'd like us to update further 👍🏻.

Thanks

**Comment by conjurer-rich** [comment]
Excellent thank you both, one minor comment on the image it says "Undefined Team Types" on the shape rather than "Undefined Team Type".
