### ISSUE TITLE
Lucid Chart template requires updating to include the Undefined Team Type shape

### ISSUE THREAD

**Issue by conjurer-rich** [TeamTopologies/Team-Shape-Templates#24]
A new Undefined Team Type shape has recently been introduced to enable a consistent representation of teams that have yet to be classified as one of the fundamental team types. 

The Lucid Chart template will need to be updated to include this.

**Comment by conjurer-rich** [comment]
@mattkoch614 is this something you could do?

**Comment by mattkoch614** [comment]
This is done, @conjurer-rich .

https://lucid.app/lucidchart/ee8afe63-92f7-4e56-8e05-f3d57846caae/edit?invitationId=inv_c87d42eb-17e4-4e8c-94a7-849d9c2c919a

**Comment by conjurer-rich** [comment]
That is great thanks
