### ISSUE TITLE
Error trying to use Lucid Chart link

### ISSUE THREAD

**Issue by tommytusj** [TeamTopologies/Team-Shape-Templates#25]
Get this message from https://lucid.app/lucidchart/xxxxxx

Sorry, you (xxxx@xxxx) don't have access to this document. You may request access after verifying your email.

**Comment by tommytusj** [comment]
pressing "Verify Email" just sends you in a loop too

**Comment by conjurer-rich** [comment]
Hey @tommytusj thanks for raising this. @mattkoch614 is this something you can look into?

**Comment by jvrdev** [comment]
I'm seeing this when accessing with my org's account 
![image](https://user-images.githubusercontent.com/1272686/162932545-8f683616-7ea8-433b-9d0e-222776dccc88.png)

**Comment by mattkoch614** [comment]
Let me take a look at what's going on.

**Comment by mattkoch614** [comment]
@tommytusj , @jvrdev - Can you try this link and see if it works for you? https://lucid.app/lucidchart/bd2d52b1-7e81-46d9-a49b-c809cf1991ae/edit?invitationId=inv_578b9974-d591-4865-b572-2fedddea8488

**Comment by tommytusj** [comment]
> @tommytusj , @jvrdev - Can you try this link and see if it works for you? https://lucid.app/lucidchart/bd2d52b1-7e81-46d9-a49b-c809cf1991ae/edit?invitationId=inv_578b9974-d591-4865-b572-2fedddea8488

works like a charm :)
