### ISSUE TITLE
Miro board template as JSON files- zip as .rtb for import to Miro

### ISSUE THREAD

**Issue by matthewskelton** [TeamTopologies/Team-Shape-Templates#5]
It would be good to version-control the Miro template properly. Luckily, the Miro board backup file (`*.rtb`) is a regular zip file containing a few files:

* images (PNG, etc.)
* `board.json` - board name, etc.
* `canvas.json` - the shapes on the canvas. **This is the main file we need for a TT shape template.**
* `meta.json` - metadata
* `resources.json` - mapping images to the canvas

Example JSON partial extract from a `canvas.json` file:

```
"shapes":[{"x":-297.6666666666667,"y":-0.22800588519339726,"rotation":0.0,"width":590.0,"height":86.0,"style":{"st":7,"ffn":10,"fs":18,"b":1,"i":0,"u":0,"s":0,"bc":16434960,"bo":0.5,"brc":16434960,"bro":1,"brw":5,"brs":2,"tc":1710618,"ta":"c","tav":"m","tsc":1,"bsc":0,"VER":2},"text":"\u003cp\u003e\u003cstrong\u003eStream-Aligned Team\u003c/strong\u003e\u003c/p\u003e","type":"7","id":3074457347789471903},{"x":-475.2655524605386,"y":458.2761723877871,"rotation":0.0,"width":234.80222841225626,"height":211.06963788300834,"style":{"st":8,"ffn":10,"fs":18,"b":1,"i":0,"u":0,"s":0,"bc":15877926,"bo":0.5,"brc":15877926,"bro":1,"brw":5,"brs":2,"tc":1710618,"ta":"c","tav":"m","tsc":0,"bsc":0,"VER":2},
```

We would then need some instructions to take the four JSON files and create a zip file with `.rtb` extension ready to be loaded into Miro.

**Comment by conjurer-rich** [comment]
I think this issue can be closed now or am I missing something?

**Comment by matthewskelton** [comment]
Agreed - this is not needed now that we have the Miro plugin.
